resources:
  repositories:
  - repository: build
    type: github
    name: eryph-org/build
    endpoint: eryph-org

trigger:
- master
- main
- refs/tags/v*

extends:
  template: pipelines/templates/dotnetclient.yml@build
  parameters:
    withCmdlet: false